version: '2'
services:
  explosig:
    depends_on:
    - explosig_server
    image: lrgr/explosig-dev:latest
    ports:
    - "8000:8080"
    environment:
    - EXPLOSIG_SERVER_URL=http://localhost:8100/
    volumes:
    - ${EXPLOSIG_DEV_PATH}/explosig/src:/src
  explosig_server:
    depends_on:
    - db
    - explosig_connect
    image: lrgr/explosig-server-dev:latest
    ports:
    - "8100:8100"
    links:
    - db
    - explosig_connect
    volumes:
    - ${EXPLOSIG_DEV_PATH}/explosig-server/obj:/obj
    - ${EXPLOSIG_DEV_PATH}/explosig-server/server:/app
    environment:
    - EXPLOSIG_PASSWORD_HASH=${EXPLOSIG_PASSWORD_HASH}
    - EXPLOSIG_DB_USER=${EXPLOSIG_DB_USER}
    - EXPLOSIG_DB_PASSWORD=${EXPLOSIG_DB_PASSWORD}
  explosig_connect:
    image: lrgr/explosig-connect-dev:latest
    ports:
    - "8200:8200"
    volumes:
    - ${EXPLOSIG_DEV_PATH}/explosig-server/connect:/app
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=${EXPLOSIG_DB_PASSWORD_ROOT}
    - MYSQL_DATABASE=explosig
    - MYSQL_USER=${EXPLOSIG_DB_USER}
    - MYSQL_PASSWORD=${EXPLOSIG_DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    volumes:
    - ${EXPLOSIG_DEV_PATH}/explosig-server/mysql:/var/lib/mysql
