version: '2'
services:
  frontend:
    depends_on:
    - backend
    image: lrgr/imuse:latest
    ports:
    - "8000:80"
  backend:
    depends_on:
    - db
    image: lrgr/imuse-server:latest
    ports:
    - "8100:80"
    links:
    - db
    volumes:
    - /path/to/your/obj:/obj
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=imuse
    - MYSQL_USER=imuse
    - MYSQL_PASSWORD=imuse
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - /path/to/your/mysql:/var/lib/mysql