version: '2'
services:
  frontend:
    depends_on:
    - backend
    image: lrgr/imuse:latest
    ports:
    - "8000:80"
    environment:
    - EXPLOSIG_SERVER_URL=http://localhost:8100/
  backend:
    depends_on:
    - db
    image: lrgr/imuse-server:latest
    ports:
    - "8100:80"
    links:
    - db
    volumes:
    - /path/to/your/obj:/obj
    environment:
    - EXPLOSIG_PASSWORD_HASH=${EXPLOSIG_PASSWORD_HASH}
    - EXPLOSIG_DB_USER=${EXPLOSIG_DB_USER}
    - EXPLOSIG_DB_PASSWORD=${EXPLOSIG_DB_PASSWORD}
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=${EXPLOSIG_DB_PASSWORD_ROOT}
    - MYSQL_DATABASE=explosig
    - MYSQL_USER=${EXPLOSIG_DB_USER}
    - MYSQL_PASSWORD=${EXPLOSIG_DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    volumes:
    - /path/to/your/mysql:/var/lib/mysql
