version: '2'
services:
  frontend:
    depends_on:
    - backend
    image: lrgr/imuse:latest
    ports:
    - "8000:80"
  backend:
    image: lrgr/imuse-server:latest
    ports:
    - "8100:80"
    volumes:
    - /path/to/your/obj:/obj
